---
title: "New_data_analysis"
author: "Ann Klezovich"
date: '8 мая 2017 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse); library(party); library(ggplot2)
```

```{r}
df <- read.csv("out.csv")
```

```{r}
sapply(df[, -c(1, 7)], table)
```

```{r}
df[, -c(1, 6, 7)] %>% 
  group_by(semantic_field,
           base,
           non_iconic,
           pattern) %>% 
  summarise(number = n()) %>% 
  arrange(desc(number)) ->
  new_df
write.csv(new_df, "aggregated_2.csv")
```

```{r}
df %>% 
  mutate(tracing = grepl("tracing", pattern),
         contour = grepl("contour", pattern),
         object = grepl("object", pattern),
         handling = grepl("handling", pattern)) %>% 
  select(6, 8:11) %>% 
  gather(key = iconicity_type, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(languages, iconicity_type) %>%
  #mutate(percentage = prop.table(n)) %>%
  ggplot(aes(languages, n, fill = iconicity_type))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Iconicity patterns in different Sign Languages")+
  theme_bw()
```

```{r}
df %>% 
  mutate(tracing = grepl("tracing", pattern),
         contour = grepl("contour", pattern),
         object = grepl("object", pattern),
         handling = grepl("handling", pattern)) %>% 
  select(6, 8:11) %>% 
  gather(key = iconicity_type, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(languages, iconicity_type) %>%
  mutate(percentage = prop.table(n)) %>%
  ggplot(aes(languages, percentage, fill = iconicity_type))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Iconicity patterns in different Sign Languages",
       y = "proportion")+
  theme_bw()
```

```{r}
df %>% 
  mutate(tracing = grepl("tracing", pattern),
         contour = grepl("contour", pattern),
         object = grepl("object", pattern),
         handling = grepl("handling", pattern)) %>% 
  select(2, 8:11) %>% 
  gather(key = iconicity_type, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(semantic_field, iconicity_type) %>% 
  mutate(percentage = prop.table(n)) %>% 
  ggplot(aes(semantic_field, percentage, fill = iconicity_type))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Iconicity patterns in different semantic fields",
       y = "proportion")+
  theme_bw()
```

```{r}
df %>% 
  mutate(form_similarity = grepl("form_similarity", base),
         assoc_action = grepl("assoc_action", base),
         parts_wholes = grepl("parts/wholes", base),
         property_holder = grepl("property/holder", base)) %>% 
  select(6, 8:11) %>% 
  gather(key = iconicity_base, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(languages, iconicity_base) %>% 
  mutate(percentage = prop.table(n)) %>% 
  ggplot(aes(languages, percentage, fill = iconicity_base))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Iconicity base in different Sign Languages",
       y = "proportion")+
  theme_bw()
```

```{r}
df %>% 
  mutate(form_similarity = grepl("form_similarity", base),
         assoc_action = grepl("assoc_action", base),
         parts_wholes = grepl("parts/wholes", base),
         property_holder = grepl("property/holder", base)) %>% 
  select(2, 8:11) %>% 
  gather(key = iconicity_base, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(semantic_field, iconicity_base) %>% 
  mutate(percentage = prop.table(n)) %>% 
  ggplot(aes(semantic_field, percentage, fill = iconicity_base))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Iconicity base in different semantic fields",
       y = "proportion")+
  theme_bw()
```

```{r}
df %>% 
  mutate(deixis = grepl("deixis", non_iconic),
         dactyl = grepl("dactyl", non_iconic),
         nonicon_and = grepl("nonicon&", non_iconic),
         nonicon = grepl("nonicon", non_iconic)) %>% 
  select(6, 8:11) %>% 
  gather(key = noniconic, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(languages, noniconic) %>% 
  #mutate(percentage = prop.table(n)) %>% 
  ggplot(aes(languages, n, fill = noniconic))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Non transparent words in different Sign Languages",
       y = "number")+
  theme_bw()
```

```{r}
df %>% 
  mutate(deixis = grepl("deixis", non_iconic),
         dactyl = grepl("dactyl", non_iconic),
         nonicon_and = grepl("nonicon&", non_iconic),
         nonicon = grepl("nonicon", non_iconic)) %>% 
  select(2, 8:11) %>% 
  gather(key = noniconic, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(semantic_field, noniconic) %>% 
  #mutate(percentage = prop.table(n)) %>% 
  ggplot(aes(semantic_field, n, fill = noniconic))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Non transparent words in different semantic fields",
       y = "number")+
  theme_bw()
```

```{r}
df %>% 
  mutate(tracing = grepl("tracing", pattern),
         contour = grepl("contour", pattern),
         object = grepl("object", pattern),
         handling = grepl("handling", pattern)) %>% 
  select(8:11) %>% 
  gather(key = iconicity_type, value = attested)%>% #, 2:5df) %>% 
  filter(attested == TRUE) %>% 
  count(iconicity_type)# %>% 
  #mutate(percentage = prop.table(n)) %>%
  #ggplot(aes(iconicity_type, fill = count(iconicity_type)))+
  #geom_bar(stat = "identity", position = "dodge")+
  #coord_flip()+
  #labs(title = "Iconicity patterns in different semantic fields",
  #     y = "number")+
  #theme_bw()
```
```{r}
df %>% 
  mutate(form_similarity = grepl("form_similarity", base),
         assoc_action = grepl("assoc_action", base),
         parts_wholes = grepl("parts/wholes", base),
         property_holder = grepl("property/holder", base)) %>% 
  select(2, 8:11) %>% 
  gather(key = iconicity_base, value = attested, 2:5) %>% 
  filter(attested == TRUE) %>% 
  count(iconicity_base) #%>% 
  #mutate(percentage = prop.table(n)) %>%
  #ggplot(aes(iconicity_type, fill = count(iconicity_type)))+
  #geom_bar(stat = "identity", position = "dodge")+
  #coord_flip()+
  #labs(title = "Iconicity patterns in different semantic fields",
  #     y = "number")+
  #theme_bw()
```
```{r}
pattern <- df$pattern[df$semantic_field=="instruments"]
languages <- df$languages[df$semantic_field=="instruments"] 
df2 <- data.frame(languages = languages, pattern = pattern)
#df2
df2 %>% 
  mutate(tracing = grepl("tracing", pattern),
         contour = grepl("contour", pattern),
         object = grepl("object", pattern),
         handling = grepl("handling", pattern)) %>%
  select(1, 3:6) %>%
  gather(key = iconicity_type, value = attested, 2:5) %>%
  filter(attested == TRUE) %>% 
  count(languages, iconicity_type) %>% 
  mutate(percentage = prop.table(n)) %>%
  ggplot(aes(languages, percentage, fill = iconicity_type))+
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  labs(title = "Cross-linguistic variance of iconicity pattern for instruments semantic field",
       y = "proportion")+
  theme_bw()
```
